
baseurl = "https://blog.vdka.me"
languageCode = "en-us"
title = "Ethan Jackwitz"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
preserveTaxonomyNames = true
footnotereturnlinkcontents = "â†©"

[permalinks]
    post = "/post/:year:month:day/:slug/"
    note = "/note/:year:month:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/"
    weight = 1

[params]
    description = "Developer."
    footer = "&copy; [Ethan Jackwitz](https://blog.vdka.me) 2017 | [Github](https://github.com/vdka) | [Twitter](https://twitter.com/ejackwitz)"
